FROM python:3.10-slim-bookworm

WORKDIR /app

COPY requirements-image-api.txt .
RUN pip install --no-cache-dir -r requirements-image-api.txt

COPY image_gen_api.py .

EXPOSE 8080

CMD ["uvicorn", "image_gen_api:app", "--host", "0.0.0.0", "--port", "8080"]