# Dockerfile_frontend

# Use a lightweight Python base image
FROM python:3.10-slim-bookworm

# Set the working directory in the container
WORKDIR /app
# Copy the requirements file and install Python dependencies
# Ensure 'requirements.txt' for the frontend is the correct name and content
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy your Streamlit application file
# Ensure 'app.py' is the correct name
COPY app.py .
# Expose the port that the Streamlit application will listen on
EXPOSE 8080
# Command to run the Streamlit application
# Streamlit runs on 0.0.0.0:8080 by default in this setup
CMD ["streamlit", "run", "app.py", "--server.port=8080", "--server.address=0.0.0.0"]